"""Seed content for Upvex v1: Data Engineering category, Apache Spark + SQL knowledge
graphs, diagnostic question banks, the v1 GenerationContract, and milestone badges.

Concept node IDs are stable slugs (not UUIDs) so gap maps in JSONB stay human-readable
and seeding stays idempotent.
"""

CATEGORY = {
    "id": "cat_data_engineering",
    "name": "Data Engineering",
    "description": "Build and operate the systems that move, store, and transform data at scale.",
}

TOPICS = [
    {
        "id": "topic_apache_spark",
        "category_id": "cat_data_engineering",
        "name": "Apache Spark",
        "description": "Distributed data processing: Spark's architecture, APIs, and performance tuning.",
    },
    {
        "id": "topic_sql",
        "category_id": "cat_data_engineering",
        "name": "SQL",
        "description": "From SELECT fundamentals to window functions, modeling, and query optimization.",
    },
]

# (id, topic_id, title, learning_objective, difficulty, bloom, duration_mins, is_root)
CONCEPT_NODES = [
    # ---------------- Apache Spark ----------------
    ("spark_big_data_fundamentals", "topic_apache_spark", "Big Data Fundamentals",
     "Explain why single-machine processing breaks down at scale and what problems distributed compute frameworks solve.",
     "beginner", "understand", 8, True),
    ("spark_distributed_storage", "topic_apache_spark", "Distributed Storage Fundamentals",
     "Describe how distributed file systems and object stores (HDFS, S3) split and replicate data, and why data locality matters.",
     "beginner", "understand", 10, True),
    ("spark_architecture", "topic_apache_spark", "Spark Architecture",
     "Identify the roles of the driver, executors, and cluster manager, and trace how a Spark application is scheduled and run.",
     "beginner", "understand", 12, False),
    ("spark_rdds", "topic_apache_spark", "RDDs and Lazy Evaluation",
     "Explain what an RDD is, how lineage enables fault tolerance, and why Spark evaluates lazily.",
     "beginner", "understand", 10, False),
    ("spark_transformations_actions", "topic_apache_spark", "Transformations vs Actions",
     "Distinguish transformations from actions and predict when a Spark job actually executes.",
     "beginner", "apply", 8, False),
    ("spark_dataframes", "topic_apache_spark", "DataFrames and the SQL API",
     "Use the DataFrame API and Spark SQL to express typical transformations, and explain how Catalyst optimizes them.",
     "intermediate", "apply", 12, False),
    ("spark_partitioning", "topic_apache_spark", "Spark Partitioning",
     "Explain how data is partitioned across executors, choose sensible partition counts, and repartition vs coalesce correctly.",
     "intermediate", "apply", 12, False),
    ("spark_shuffles", "topic_apache_spark", "Shuffles and Wide Dependencies",
     "Identify which operations trigger shuffles, why shuffles are expensive, and how to minimize them.",
     "intermediate", "analyse", 12, False),
    ("spark_joins", "topic_apache_spark", "Join Strategies",
     "Compare broadcast, sort-merge, and shuffle-hash joins and choose the right strategy for skewed or large datasets.",
     "advanced", "analyse", 12, False),
    ("spark_caching", "topic_apache_spark", "Caching and Persistence",
     "Decide when to cache or persist a DataFrame, choose a storage level, and avoid common caching pitfalls.",
     "intermediate", "apply", 10, False),
    ("spark_memory_management", "topic_apache_spark", "Memory Management",
     "Describe Spark's unified memory model (execution vs storage) and diagnose out-of-memory failures.",
     "advanced", "analyse", 12, False),
    ("spark_optimization", "topic_apache_spark", "Performance Tuning and Optimization",
     "Read the Spark UI and query plans to find bottlenecks, and apply tuning levers: partitioning, AQE, broadcast hints, skew handling.",
     "advanced", "analyse", 15, False),
    ("spark_streaming", "topic_apache_spark", "Structured Streaming",
     "Build an incremental pipeline with Structured Streaming, explaining micro-batches, watermarks, and output modes.",
     "advanced", "apply", 15, False),
    ("spark_deployment", "topic_apache_spark", "Deployment and Cluster Sizing",
     "Choose deploy modes and right-size executors (cores, memory, instances) for a given workload.",
     "advanced", "apply", 12, False),

    # ---------------- SQL ----------------
    ("sql_relational_model", "topic_sql", "The Relational Model",
     "Explain tables, rows, keys, and relationships, and why relational databases enforce schemas.",
     "beginner", "understand", 8, True),
    ("sql_select_basics", "topic_sql", "SELECT Fundamentals",
     "Write SELECT queries with projections, aliases, ordering, and LIMIT.",
     "beginner", "apply", 8, False),
    ("sql_filtering", "topic_sql", "Filtering and Predicates",
     "Filter rows with WHERE using comparison, logical, range, set, and pattern predicates, handling NULL correctly.",
     "beginner", "apply", 8, False),
    ("sql_aggregations", "topic_sql", "Aggregations and GROUP BY",
     "Summarize data with aggregate functions and GROUP BY, and filter groups with HAVING.",
     "beginner", "apply", 10, False),
    ("sql_joins", "topic_sql", "Joins",
     "Combine tables with INNER, LEFT, RIGHT, and FULL joins and predict row counts for each.",
     "intermediate", "apply", 12, False),
    ("sql_subqueries", "topic_sql", "Subqueries and CTEs",
     "Structure multi-step logic with subqueries and common table expressions, including correlated subqueries.",
     "intermediate", "apply", 12, False),
    ("sql_window_functions", "topic_sql", "Window Functions",
     "Use OVER with PARTITION BY and ORDER BY for rankings, running totals, and offsets without collapsing rows.",
     "intermediate", "apply", 12, False),
    ("sql_data_modeling", "topic_sql", "Normalization and Data Modeling",
     "Apply normal forms to reduce redundancy and decide when denormalization is justified for analytics.",
     "intermediate", "analyse", 12, False),
    ("sql_indexes", "topic_sql", "Indexes and Query Performance",
     "Explain how B-tree indexes speed up lookups, when indexes help or hurt, and how to spot missing-index symptoms.",
     "intermediate", "analyse", 10, False),
    ("sql_transactions", "topic_sql", "Transactions and Isolation",
     "Describe ACID properties and isolation levels, and reason about anomalies like dirty and phantom reads.",
     "intermediate", "understand", 10, False),
    ("sql_query_optimization", "topic_sql", "Query Optimization and Execution Plans",
     "Read execution plans (EXPLAIN) to identify scans, join order, and misestimates, and rewrite queries for performance.",
     "advanced", "analyse", 15, False),
    ("sql_advanced_analytics", "topic_sql", "Advanced Analytical Patterns",
     "Solve gaps-and-islands, sessionization, and pivot problems by combining window functions and CTEs.",
     "advanced", "analyse", 15, False),
]

# (from_concept_id = prerequisite, to_concept_id = dependent, edge_type)
CONCEPT_EDGES = [
    # Spark
    ("spark_big_data_fundamentals", "spark_architecture", "required"),
    ("spark_distributed_storage", "spark_partitioning", "required"),
    ("spark_architecture", "spark_rdds", "required"),
    ("spark_rdds", "spark_transformations_actions", "required"),
    ("spark_rdds", "spark_dataframes", "required"),
    ("spark_dataframes", "spark_partitioning", "required"),
    ("spark_transformations_actions", "spark_shuffles", "required"),
    ("spark_partitioning", "spark_shuffles", "required"),
    ("spark_shuffles", "spark_joins", "required"),
    ("spark_dataframes", "spark_caching", "required"),
    ("spark_partitioning", "spark_caching", "recommended"),
    ("spark_architecture", "spark_memory_management", "required"),
    ("spark_caching", "spark_memory_management", "recommended"),
    ("spark_shuffles", "spark_optimization", "required"),
    ("spark_memory_management", "spark_optimization", "required"),
    ("spark_joins", "spark_optimization", "recommended"),
    ("spark_dataframes", "spark_streaming", "required"),
    ("spark_partitioning", "spark_streaming", "recommended"),
    ("spark_architecture", "spark_deployment", "required"),
    ("spark_optimization", "spark_deployment", "recommended"),
    # SQL
    ("sql_relational_model", "sql_select_basics", "required"),
    ("sql_select_basics", "sql_filtering", "required"),
    ("sql_filtering", "sql_aggregations", "required"),
    ("sql_filtering", "sql_joins", "required"),
    ("sql_joins", "sql_subqueries", "required"),
    ("sql_aggregations", "sql_subqueries", "required"),
    ("sql_aggregations", "sql_window_functions", "required"),
    ("sql_subqueries", "sql_window_functions", "recommended"),
    ("sql_relational_model", "sql_data_modeling", "required"),
    ("sql_joins", "sql_data_modeling", "required"),
    ("sql_joins", "sql_indexes", "required"),
    ("sql_relational_model", "sql_transactions", "required"),
    ("sql_indexes", "sql_query_optimization", "required"),
    ("sql_subqueries", "sql_query_optimization", "required"),
    ("sql_window_functions", "sql_advanced_analytics", "required"),
    ("sql_subqueries", "sql_advanced_analytics", "recommended"),
]

# Diagnostic question bank.
# (topic_id, concept_node_id, difficulty, type, question_text, options, correct_option, expected_concepts)
DIAGNOSTIC_QUESTIONS = [
    # ---- Spark: big data fundamentals ----
    ("topic_apache_spark", "spark_big_data_fundamentals", "easy", "multiple_choice",
     "What is the main reason single-machine data processing fails at large scale?",
     ["The CPU instruction set differs on servers",
      "Data no longer fits in one machine's memory/disk and processing time grows beyond practical limits",
      "Operating systems limit files to 2 GB",
      "Single machines cannot run Python"],
     1, None),
    ("topic_apache_spark", "spark_big_data_fundamentals", "medium", "multiple_choice",
     "Horizontal scaling means:",
     ["Buying a bigger machine with more RAM",
      "Adding more machines and distributing work across them",
      "Compressing data before processing",
      "Using a faster programming language"],
     1, None),
    # ---- Spark: distributed storage ----
    ("topic_apache_spark", "spark_distributed_storage", "easy", "multiple_choice",
     "In HDFS, large files are:",
     ["Stored whole on one node with a backup tape",
      "Split into blocks that are replicated across multiple nodes",
      "Compressed into a single ZIP archive",
      "Always kept in memory"],
     1, None),
    ("topic_apache_spark", "spark_distributed_storage", "medium", "multiple_choice",
     "Why does 'data locality' matter in distributed processing?",
     ["It keeps data sorted alphabetically",
      "Moving computation to where data lives avoids expensive network transfer of large datasets",
      "It guarantees exactly-once semantics",
      "It is required for SQL support"],
     1, None),
    ("topic_apache_spark", "spark_distributed_storage", "hard", "short_answer",
     "A team switches from HDFS to S3 for their data lake. Name one property they lose or must handle differently, and why it affects processing jobs.",
     None, None, ["data locality", "eventual consistency", "rename", "listing", "throughput", "object store"]),
    # ---- Spark: architecture ----
    ("topic_apache_spark", "spark_architecture", "easy", "multiple_choice",
     "In a Spark application, which component builds the execution plan and coordinates work?",
     ["The executor", "The driver", "The cluster manager", "The shuffle service"],
     1, None),
    ("topic_apache_spark", "spark_architecture", "medium", "multiple_choice",
     "What is the role of executors in Spark?",
     ["They schedule other applications on the cluster",
      "They run tasks and hold cached data on worker nodes",
      "They store the Hive metastore",
      "They compile SQL to Java"],
     1, None),
    ("topic_apache_spark", "spark_architecture", "hard", "multiple_choice",
     "If the Spark driver process dies mid-job (client deploy mode, no supervision), what happens?",
     ["Executors finish the job and write results",
      "The application fails — executors are released because coordination is lost",
      "The cluster manager restarts only the failed stage",
      "Nothing; drivers are optional"],
     1, None),
    # ---- Spark: RDDs ----
    ("topic_apache_spark", "spark_rdds", "easy", "multiple_choice",
     "What does RDD lineage enable?",
     ["Faster serialization", "Recomputing lost partitions after a failure", "SQL support", "Smaller cluster sizes"],
     1, None),
    ("topic_apache_spark", "spark_rdds", "medium", "multiple_choice",
     "Lazy evaluation in Spark means:",
     ["Spark waits 60 seconds before starting jobs",
      "Transformations build a plan that only executes when an action is called",
      "Executors sleep between tasks",
      "Results are cached automatically"],
     1, None),
    # ---- Spark: transformations vs actions ----
    ("topic_apache_spark", "spark_transformations_actions", "easy", "multiple_choice",
     "Which of these is an action (triggers execution)?",
     ["filter()", "select()", "count()", "withColumn()"],
     2, None),
    ("topic_apache_spark", "spark_transformations_actions", "medium", "multiple_choice",
     "A pipeline applies ten transformations then calls collect() twice with no caching. How many times is the transformation chain computed?",
     ["Once", "Twice", "Ten times", "Zero times"],
     1, None),
    # ---- Spark: dataframes ----
    ("topic_apache_spark", "spark_dataframes", "easy", "multiple_choice",
     "The main advantage of DataFrames over raw RDDs is:",
     ["They can hold more rows",
      "Schema awareness lets the Catalyst optimizer plan and optimize queries",
      "They avoid the JVM entirely",
      "They are always cached"],
     1, None),
    ("topic_apache_spark", "spark_dataframes", "medium", "multiple_choice",
     "df.groupBy(\"country\").agg(sum(\"revenue\")) — what does Catalyst do with this?",
     ["Executes it immediately row by row",
      "Builds a logical plan, optimizes it, and compiles a physical plan executed lazily",
      "Sends it to an external SQL database",
      "Converts it to a Python UDF"],
     1, None),
    ("topic_apache_spark", "spark_dataframes", "hard", "short_answer",
     "Why do Python UDFs typically perform worse than built-in Spark SQL functions on DataFrames?",
     None, None, ["serialization", "catalyst", "optimizer", "jvm", "python worker", "vectorized", "opaque"]),
    # ---- Spark: partitioning ----
    ("topic_apache_spark", "spark_partitioning", "easy", "multiple_choice",
     "A partition in Spark is:",
     ["A separate database table",
      "A chunk of a dataset processed by a single task",
      "A backup copy of data",
      "A section of the Spark UI"],
     1, None),
    ("topic_apache_spark", "spark_partitioning", "medium", "multiple_choice",
     "You have 2 partitions holding 500 GB total and 200 available cores. What's the main problem?",
     ["Too much parallelism",
      "Only 2 tasks can run, leaving 198 cores idle and each task handling 250 GB",
      "The data will be duplicated 200 times",
      "Spark will refuse to start"],
     1, None),
    ("topic_apache_spark", "spark_partitioning", "hard", "multiple_choice",
     "When reducing 1000 partitions to 10 for output, why prefer coalesce(10) over repartition(10)?",
     ["coalesce guarantees sorted output",
      "coalesce avoids a full shuffle by merging existing partitions in place",
      "repartition drops rows",
      "coalesce compresses the data"],
     1, None),
    # ---- Spark: shuffles ----
    ("topic_apache_spark", "spark_shuffles", "easy", "multiple_choice",
     "Which operation always triggers a shuffle?",
     ["filter()", "map()", "groupBy().agg() on a non-partitioned column", "select()"],
     2, None),
    ("topic_apache_spark", "spark_shuffles", "medium", "multiple_choice",
     "Why are shuffles expensive?",
     ["They require writing data to the driver",
      "Data is redistributed across the network and written to disk between stages",
      "They lock the cluster manager",
      "They disable the Catalyst optimizer"],
     1, None),
    ("topic_apache_spark", "spark_shuffles", "hard", "short_answer",
     "A job has one stage that is much slower than the rest, and one task in that stage takes 10x longer than its siblings. What is the likely cause and one way to fix it?",
     None, None, ["skew", "salting", "aqe", "adaptive", "hot key", "repartition", "broadcast"]),
    # ---- Spark: joins ----
    ("topic_apache_spark", "spark_joins", "medium", "multiple_choice",
     "When is a broadcast join the right choice?",
     ["When both tables are over 1 TB",
      "When one table is small enough to fit in each executor's memory",
      "When the join key is a string",
      "Never; sort-merge is always better"],
     1, None),
    ("topic_apache_spark", "spark_joins", "hard", "multiple_choice",
     "Joining two large tables on a key where 40% of rows share one value. The join stalls on a few tasks. Best mitigation?",
     ["Increase driver memory",
      "Salt the skewed key (or enable AQE skew join handling) to split the hot partition",
      "Convert to RDDs",
      "Use collect() then join in Python"],
     1, None),
    # ---- Spark: caching ----
    ("topic_apache_spark", "spark_caching", "easy", "multiple_choice",
     "When is caching a DataFrame most useful?",
     ["When it is used once and discarded",
      "When it is reused across multiple actions or iterations",
      "When it is written straight to disk",
      "Always — caching is free"],
     1, None),
    ("topic_apache_spark", "spark_caching", "medium", "multiple_choice",
     "What happens if a cached DataFrame doesn't fit in memory with MEMORY_AND_DISK storage level?",
     ["The job fails with OOM",
      "Partitions that don't fit spill to disk and are read back when needed",
      "Spark silently drops the extra rows",
      "The cache is disabled cluster-wide"],
     1, None),
    # ---- Spark: memory management ----
    ("topic_apache_spark", "spark_memory_management", "medium", "multiple_choice",
     "Spark's unified memory region is shared between:",
     ["Driver heap and executor heap",
      "Execution memory (shuffles, joins, sorts) and storage memory (cache)",
      "JVM and Python",
      "HDFS blocks and S3 objects"],
     1, None),
    ("topic_apache_spark", "spark_memory_management", "hard", "short_answer",
     "An executor keeps dying with OOM during a large aggregation. Give two levers you would try and why.",
     None, None, ["partitions", "spark.sql.shuffle.partitions", "executor memory", "memory fraction", "spill", "skew", "off-heap", "fewer cores"]),
    # ---- Spark: optimization ----
    ("topic_apache_spark", "spark_optimization", "medium", "multiple_choice",
     "In the Spark UI, a stage shows 200 tasks where median duration is 2s but max is 4min. This indicates:",
     ["Healthy parallelism", "Data skew in that stage's partitioning key", "Too much caching", "A driver bottleneck"],
     1, None),
    ("topic_apache_spark", "spark_optimization", "hard", "multiple_choice",
     "What does Adaptive Query Execution (AQE) do?",
     ["Rewrites Python code to Scala",
      "Re-optimizes the plan at runtime using actual stage statistics (e.g. coalescing partitions, switching join strategies)",
      "Automatically adds more executors",
      "Caches every intermediate result"],
     1, None),
    # ---- Spark: streaming ----
    ("topic_apache_spark", "spark_streaming", "medium", "multiple_choice",
     "Structured Streaming processes data primarily as:",
     ["One record at a time with per-record acknowledgements",
      "Incremental micro-batches over an unbounded table abstraction",
      "Hourly cron jobs",
      "A single batch at shutdown"],
     1, None),
    ("topic_apache_spark", "spark_streaming", "hard", "multiple_choice",
     "What problem do watermarks solve in Structured Streaming?",
     ["Slow file listing on S3",
      "Bounding state for late-arriving events so aggregation state can be dropped safely",
      "Executor memory leaks",
      "Schema evolution"],
     1, None),
    # ---- Spark: deployment ----
    ("topic_apache_spark", "spark_deployment", "medium", "multiple_choice",
     "In cluster deploy mode, the driver runs:",
     ["On the user's laptop",
      "Inside the cluster on a worker node",
      "On the cluster manager master only",
      "There is no driver in cluster mode"],
     1, None),
    ("topic_apache_spark", "spark_deployment", "hard", "multiple_choice",
     "Why are very large executors (e.g. 64 cores, 512 GB) usually a bad idea?",
     ["Spark caps executors at 8 cores",
      "GC pauses grow with heap size and HDFS client concurrency suffers beyond ~5 cores per executor",
      "They cost the same as small ones",
      "The driver cannot address them"],
     1, None),

    # ---- SQL: relational model ----
    ("topic_sql", "sql_relational_model", "easy", "multiple_choice",
     "A primary key:",
     ["Orders the table alphabetically",
      "Uniquely identifies each row in a table",
      "Encrypts the row",
      "Is always an auto-incrementing integer"],
     1, None),
    ("topic_sql", "sql_relational_model", "medium", "multiple_choice",
     "A foreign key enforces:",
     ["Uniqueness within its own table",
      "Referential integrity — values must exist in the referenced table",
      "Faster SELECT queries",
      "Column-level encryption"],
     1, None),
    # ---- SQL: select basics ----
    ("topic_sql", "sql_select_basics", "easy", "multiple_choice",
     "Which query returns the 10 most expensive products?",
     ["SELECT * FROM products ORDER BY price ASC LIMIT 10",
      "SELECT * FROM products ORDER BY price DESC LIMIT 10",
      "SELECT TOP price FROM products",
      "SELECT * FROM products WHERE price = MAX"],
     1, None),
    ("topic_sql", "sql_select_basics", "medium", "multiple_choice",
     "What does SELECT DISTINCT city FROM users do?",
     ["Returns every row with its city",
      "Returns each unique city once",
      "Returns cities sorted by frequency",
      "Deletes duplicate rows from the table"],
     1, None),
    # ---- SQL: filtering ----
    ("topic_sql", "sql_filtering", "easy", "multiple_choice",
     "Which WHERE clause finds rows where email is missing?",
     ["WHERE email = NULL", "WHERE email IS NULL", "WHERE email == NONE", "WHERE NOT email"],
     1, None),
    ("topic_sql", "sql_filtering", "medium", "multiple_choice",
     "WHERE status NOT IN ('active', 'trial') — a row with status NULL is:",
     ["Included, because NULL isn't in the list",
      "Excluded, because NULL comparisons yield UNKNOWN which fails the filter",
      "Included twice",
      "Causes a query error"],
     1, None),
    ("topic_sql", "sql_filtering", "hard", "short_answer",
     "Explain the difference between filtering in WHERE vs filtering in HAVING, and when each executes.",
     None, None, ["rows", "groups", "before", "after", "group by", "aggregate"]),
    # ---- SQL: aggregations ----
    ("topic_sql", "sql_aggregations", "easy", "multiple_choice",
     "COUNT(*) vs COUNT(email): the difference is that COUNT(email)…",
     ["Counts unique emails only",
      "Excludes rows where email is NULL",
      "Is always equal to COUNT(*)",
      "Counts characters in each email"],
     1, None),
    ("topic_sql", "sql_aggregations", "medium", "multiple_choice",
     "Which query finds countries with more than 100 users?",
     ["SELECT country FROM users WHERE COUNT(*) > 100",
      "SELECT country FROM users GROUP BY country HAVING COUNT(*) > 100",
      "SELECT country, COUNT(*) FROM users HAVING country > 100",
      "SELECT DISTINCT country FROM users WHERE users > 100"],
     1, None),
    # ---- SQL: joins ----
    ("topic_sql", "sql_joins", "easy", "multiple_choice",
     "A LEFT JOIN from orders to customers returns:",
     ["Only orders that have a matching customer",
      "All orders, with customer columns NULL where no match exists",
      "All customers, with order columns NULL where no match exists",
      "The cartesian product"],
     1, None),
    ("topic_sql", "sql_joins", "medium", "multiple_choice",
     "Table A has 5 rows, table B has 3 rows, and the join key matches 2 rows in both (1:1). INNER JOIN returns how many rows?",
     ["15", "5", "3", "2"],
     3, None),
    ("topic_sql", "sql_joins", "hard", "short_answer",
     "You LEFT JOIN payments to orders and the row count unexpectedly increases. What happened and how do you fix it?",
     None, None, ["duplicate", "one-to-many", "fan out", "many", "aggregate", "deduplicate", "distinct", "grain"]),
    # ---- SQL: subqueries ----
    ("topic_sql", "sql_subqueries", "medium", "multiple_choice",
     "A CTE (WITH clause) is best described as:",
     ["A temporary index",
      "A named subquery that makes multi-step logic readable and reusable within one statement",
      "A stored procedure",
      "A materialized table on disk"],
     1, None),
    ("topic_sql", "sql_subqueries", "hard", "multiple_choice",
     "A correlated subquery differs from a plain subquery because it:",
     ["Runs only once regardless of outer rows",
      "References columns of the outer query, so it's logically evaluated per outer row",
      "Cannot appear in WHERE clauses",
      "Always returns multiple columns"],
     1, None),
    # ---- SQL: window functions ----
    ("topic_sql", "sql_window_functions", "medium", "multiple_choice",
     "What does ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at) produce?",
     ["A global row count",
      "A per-user sequence numbering each user's rows by time",
      "The number of partitions",
      "A random ordering"],
     1, None),
    ("topic_sql", "sql_window_functions", "medium", "multiple_choice",
     "The key difference between GROUP BY and a window function is:",
     ["Window functions are faster",
      "GROUP BY collapses rows; window functions compute aggregates while keeping every row",
      "GROUP BY works only on numbers",
      "There is no difference"],
     1, None),
    ("topic_sql", "sql_window_functions", "hard", "short_answer",
     "How would you select each customer's most recent order using a window function? Describe the approach.",
     None, None, ["row_number", "rank", "partition by", "order by", "desc", "filter", "qualify", "= 1"]),
    # ---- SQL: data modeling ----
    ("topic_sql", "sql_data_modeling", "medium", "multiple_choice",
     "Storing a customer's address in every order row (instead of a customers table) violates:",
     ["First normal form", "Normalization principles — it duplicates data and risks update anomalies", "The SQL standard", "ACID"],
     1, None),
    ("topic_sql", "sql_data_modeling", "hard", "multiple_choice",
     "In analytics warehouses, star schemas intentionally denormalize because:",
     ["Normalization is deprecated",
      "Fewer joins and wide fact/dimension tables favor read-heavy analytical queries",
      "Storage is more expensive than compute",
      "BI tools cannot join tables"],
     1, None),
    # ---- SQL: indexes ----
    ("topic_sql", "sql_indexes", "medium", "multiple_choice",
     "A B-tree index on users(email) most helps which query?",
     ["SELECT * FROM users",
      "SELECT * FROM users WHERE email = 'a@b.com'",
      "SELECT COUNT(*) FROM users",
      "UPDATE users SET email = NULL"],
     1, None),
    ("topic_sql", "sql_indexes", "hard", "multiple_choice",
     "Why can too many indexes hurt performance?",
     ["They make SELECT queries slower by default",
      "Every INSERT/UPDATE/DELETE must maintain each index, adding write overhead",
      "They corrupt statistics",
      "Databases allow at most five indexes"],
     1, None),
    # ---- SQL: transactions ----
    ("topic_sql", "sql_transactions", "medium", "multiple_choice",
     "Atomicity in ACID means:",
     ["Transactions run one at a time",
      "All statements in a transaction commit together or none do",
      "Data is stored in atomic (smallest) units",
      "Reads never block writes"],
     1, None),
    ("topic_sql", "sql_transactions", "hard", "multiple_choice",
     "A 'dirty read' happens when a transaction:",
     ["Reads rows written by another transaction that hasn't committed yet",
      "Reads the same row twice with different results after another commit",
      "Sees new rows matching its filter on re-read",
      "Reads from a corrupted page"],
     0, None),
    # ---- SQL: query optimization ----
    ("topic_sql", "sql_query_optimization", "medium", "multiple_choice",
     "EXPLAIN shows a sequential scan on a 100M-row table filtered by an indexed column. A common cause is:",
     ["The table is too small",
      "A function or type cast wrapped around the column prevents index use",
      "EXPLAIN disables indexes",
      "Sequential scans are always chosen for SELECTs"],
     1, None),
    ("topic_sql", "sql_query_optimization", "hard", "short_answer",
     "A query joining three tables is slow. Describe two things you would look for in the execution plan.",
     None, None, ["join order", "scan", "index", "estimate", "rows", "nested loop", "hash join", "spill", "statistics", "cardinality"]),
    # ---- SQL: advanced analytics ----
    ("topic_sql", "sql_advanced_analytics", "hard", "multiple_choice",
     "The 'gaps and islands' problem is typically solved with:",
     ["Recursive triggers",
      "Difference of row numbers to group consecutive sequences",
      "A CROSS JOIN against a calendar table only",
      "Materialized views"],
     1, None),
    ("topic_sql", "sql_advanced_analytics", "hard", "multiple_choice",
     "Sessionizing clickstream events (new session after 30 min inactivity) is done by:",
     ["GROUP BY user_id only",
      "LAG() to compute inactivity gaps, flag session starts, then a running SUM to assign session IDs",
      "Random sampling",
      "A FULL OUTER JOIN on timestamps"],
     1, None),
]

GENERATION_CONTRACT_V1 = {
    "version": 1,
    "persona_text": (
        "You are Upvex's learning guide: a sharp, encouraging mentor for tech skills. "
        "Explain concepts clearly and concretely, using real-world data engineering scenarios and "
        "one well-chosen analogy where it genuinely aids understanding (never forced). "
        "Adapt tone to the learner's stated preference: 'playful' allows light humor and energy, "
        "'professional' stays crisp and workplace-neutral, 'neutral' is friendly but plain. "
        "Encourage without condescending. Never use emojis."
    ),
    "structural_template": (
        "LESSON SHAPE (JSON): a lesson has: 'title' (string), 'intro' (2-3 sentences framing why this "
        "concept matters), 'sections' (array of 2-4 objects with 'heading', 'body' in markdown, and optional "
        "'code_example' with 'language' and 'code' for read/analyze snippets only — never exercises requiring "
        "execution), 'key_takeaways' (array of 3-5 strings), and 'check_understanding' (one reflective "
        "question, string). "
        "QUIZ SHAPE (JSON): a quiz has 'questions': array of exactly 4 objects, each with 'type' "
        "('multiple_choice' x3 and 'short_answer' x1), 'question_text', 'options' (4 strings, multiple_choice "
        "only), 'correct_option' (0-based index, multiple_choice only), 'expected_concepts' (array of "
        "keywords, short_answer only), and 'explanation' (why the answer is correct)."
    ),
    "constraints_text": (
        "Stay strictly on the stated learning objective of this concept node. Do not wander into adjacent "
        "concepts beyond one-sentence pointers. If a technical specific is uncertain or version-dependent, "
        "say so rather than asserting it confidently. Target 5-10 minutes of reading. Output MUST be valid "
        "JSON matching the defined schema exactly — no markdown fences, no commentary outside the JSON."
    ),
}

BADGES = [
    {"id": "badge_first_lesson", "name": "Liftoff", "description": "Complete your first lesson.",
     "criteria": {"type": "first_lesson"}},
    {"id": "badge_root_gap_resolved", "name": "Root Cause", "description": "Resolve a root gap concept — the foundation unlocks everything above it.",
     "criteria": {"type": "root_gap_resolved"}},
    {"id": "badge_five_concepts", "name": "Momentum", "description": "Complete 5 concepts in a single topic.",
     "criteria": {"type": "concepts_completed", "count": 5}},
    {"id": "badge_cluster_master", "name": "Cluster Master", "description": "Complete 10 concepts in a single topic.",
     "criteria": {"type": "concepts_completed", "count": 10}},
    {"id": "badge_week_streak", "name": "Vector Locked", "description": "Keep a 7-day learning streak.",
     "criteria": {"type": "streak_days", "days": 7}},
]
